[workspace]
authors = ["Jan Eglinger <jan.eglinger@fmi.ch>"]
channels = ["conda-forge"]
name = "pixi-assistant"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
rust = ">=1.91.1,<1.92"
